### ISSUE TITLE
Does not work with Gradle 2.14-rc-1

### ISSUE THREAD

**Issue by madisp** [xvik/gradle-animalsniffer-plugin#1]
I get the following trace:

```
Caused by: java.lang.IncompatibleClassChangeError
        at ru.vyarus.gradle.plugin.animalsniffer.AnimalSnifferPlugin.createConfigurations(AnimalSnifferPlugin.groovy:41)
        at org.gradle.api.plugins.quality.internal.AbstractCodeQualityPlugin.apply(AbstractCodeQualityPlugin.java:57)
        at org.gradle.api.plugins.quality.internal.AbstractCodeQualityPlugin.apply(AbstractCodeQualityPlugin.java:42)
```

**Comment by xvik** [comment]
To fix the issue I need to rebuild plugin with gradle 2.14 (plugin base class (AbstractCodeQualityPlugin) become java class instead of groovy). 
I will wait for gradle 2.14 release (to be sure) and release new plugin version immediately.

**Comment by xvik** [comment]
[1.1.0](https://github.com/xvik/gradle-animalsniffer-plugin/releases/tag/1.1.0) released
