### ISSUE TITLE
Deprecation warning in Gradle 5.0+

### ISSUE THREAD

**Issue by szpak** [xvik/gradle-animalsniffer-plugin#12]
I've got the following warning building my project with 1.4.6 applied:

```
The TaskContainer.remove(Object) method has been deprecated.
    This is scheduled to be removed in Gradle 6.0. Prefer disabling the task instead,
    see Task.setEnabled(boolean).
        at org.gradle.api.internal.tasks.DefaultTaskContainer.warnAboutRemoveMethodDeprecation(DefaultTaskContainer.java:625)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.remove(DefaultTaskContainer.java:564)
        at java_util_Set$remove$5.call(Unknown Source)
        at ru.vyarus.gradle.plugin.animalsniffer.AnimalSnifferPlugin$_configureCheckTask_closure12.doCall(AnimalSnifferPlugin.groovy:177)
        at jdk.internal.reflect.GeneratedMethodAccessor327.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:411)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure$1$1.run(DefaultListenerBuildOperationDecorator.java:188)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:58)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure$1.run(DefaultListenerBuildOperationDecorator.java:183)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure.doCall(DefaultListenerBuildOperationDecorator.java:180)
        at jdk.internal.reflect.GeneratedMethodAccessor274.invoke(Unknown Source)
(...)
```

**Comment by xvik** [comment]
Thank you!
There were actually incompatible gradle api changes, so new version will work only on gradle 5+.
I will release it today or tomorrow.
